### ISSUE TITLE
I'm Updating user meta using WP Background Processing

### ISSUE THREAD

**Issue by Usama5226** [deliciousbrains/wp-background-processing#109]
Hi @A5hleyRich & @ianmjones,

I am trying to update the user meta from the CSV file.

I have just updated the handle_all() and task() functions to update the user meta it is updating the user but the issue is that after updating about 1000 users I think the server is sleep for some time and when the query runs again instead of where it left is start from the begin of the CVS file and again updating the saved user.
```
protected function handle_all() {
		$upload_dir    = wp_upload_dir();
    	$csv_file_path = $upload_dir['basedir'] . '/feedback/user.csv';
    	$this->process_all->push_to_queue(array('csv_file' => $csv_file_path));
    	$this->process_all->save()->dispatch();
    	error_log('handle all');
	}
```
```
	protected function task($data) {
        if (empty($data['csv_file'])) {
            return false;
        }

        $csv_file = $data['csv_file'];

        if (($handle = fopen($csv_file, 'r')) !== false) {
            $user_license_expirations = array();

            while (($data = fgetcsv($handle)) !== false) {
             $meta_data = array(
				'first_name'                 => $data[1],
				'last_name'                  => $data[2],
				'nickname'                   => $data[3],
				'display_name'               => $data[3],
				'user_nicename'              => $data[3],
				'user_email'                 => $data[4],
				'registered'                 => $data[6],
				'shipping_address_1'         => $data[14],
				'shipping_city'              => $data[15],
				'shipping_state'             => $data[16],
				'shipping_postcode'          => $data[17],
				'shipping_phone'             => $data[18],
				'student_detail_phone'       => $data[18],
				'student_license_number'     => $data[5],
				'student_state_of_license'   => $data[16],
				'billing_first_name'         => $data[1],
				'shipping_first_name'        => $data[12],
				'billing_address_1'          => $data[7],
				'billing_city'               => $data[8],
				'billing_state'              => $data[9],
				'billing_postcode'           => $data[10],
				'billing_phone'              => $data[11],
				'billing_email'              => $data[4],
				'student_detail_email'       => $data[13],
				'student_license_expiration' => $data[24],
				'being_upload_from_csv' => 1,
			);
                $user = get_user_by('email', $data[4]);
				error_log(print_r($data[4], true ));
                if ($user) {
                   foreach ( $meta_data as $meta_key => $meta_value ) {
					update_user_meta( $user->ID, $meta_key, $meta_value );
				}
					ld_update_course_access( $user->ID, $data[23] );
					$user_license_expirations[$user->ID][] = $data[24];
					if ( $data[25] == 1 ) {
						update_user_meta( $user->ID, 'course_' . $data[23] . '_quota', 0 );
						update_user_meta($user->ID, 'course_completed_'.$data[23], time());
						learndash_process_mark_complete( $user->ID, $data[23], true);
					} else {
						update_user_meta( $user->ID, 'course_' . $data[23] . '_quota', 1 );
					}
                }
            }

            fclose($handle);

            // Update all users with the newest license expiration date
            foreach ($user_license_expirations as $user_id => $expirations) {
                $newest_expiration = max($expirations);
                update_user_meta($user_id, 'student_license_expiration', $newest_expiration);
            }
        }

        // $this->really_long_running_task(); // Call your long-running task here
        $this->log('User meta update task completed.');
		    	error_log('user updated');
        return false;
    }
```

Could you please help?
Thanks.

**Comment by ianmjones** [comment]
Your while loop in `task()` is overwriting the passed in `$data` variable, you really don't want to do that. I recommend using `$item` for the `task()` param.

As you process each record in the while loop's `$data`, update something like a `last_row_processed` field in the `$item`, and then return the `$item`.

At the top of the while loop, if the `$item` has that `last_row_processed`, keep skipping until you're on the next row number to be processed, as otherwise you'll be processing every row over and over again on restart.

At some point you'll not process anything and skip all the way through the file without processing anything and drop out of the loop and return `false` to close out the batch. You could instead keep track of how many rows there are in the file, and when you're updating the `last_row_processed` to match the count, return `false` to close out the batch.

An alternate strategy to keeping tabs of the last processed row in the item is to actually remove data from the CSV as it is process, then you'll just be processing the file row by row, removing the processed row, returning the same `$item` until the file is empty, when you then return `false` to close out the batch.

But the best strategy might be to load the CSV right at the beginning in `handle_all()`, and enqueue each row before the save and dispatch. Then each `$item` passed to `task()` will be a row to be processed. You just return `false` after processing each `$item` to have it removed from the batch, no while loop required in `task()`. That's the canonical way to do it.

If you have a super large CSV file to be processed, you could enqueue say 1,000 rows before each `save()` to safely split the workload across a number of smaller batches before doing the `dispatch` to start the processing. Each batch of 1,000 will be picked up and processed item by item in turn. I personally would be tempted to do a `save()` for each row of the CSV so that each has its own batch record.

Hope that helps.

**Comment by Usama5226** [comment]
Thanks for your reply,

I have about 32000 users which I need to update. Could you please give me
some examples for the best strategy for this task?

Really thankful for your help.
