### ISSUE TITLE
When a job is released should it reserialize so state can be preserved?

### ISSUE THREAD

**Issue by rsouthgate** [deliciousbrains/wp-background-processing#15]
I note in the master branch when using the task method the object passed around could be manipulated so multiple passes over the same object could save state and pick up where the previous task left off.

Moving to the queue and handle branch I see the job gets serialized to the db when it's pushed to the queue, but if I want to just do a part of the job and then release back to the queue I can't preserve state within the job because the next time the queue reaches it the job is deserialized from the original push.

So I'm wondering if I'm doing it wrong and should be preserving the state of the job outside of it, or should it be serialized and written back to db when released back to the queue?

**Comment by ianmjones** [comment]
This may have been improved since this issue was raised, but in v1.0.2, when `\WP_Background_Process::task()` passes back an item as it is not finished with and needs to be processed later, it should be in a state that makes sense to pick up in the future.

The incomplete queued item will be saved back to the batch ready to be picked up next time.
