### ISSUE TITLE
Usually the background processes start quickly, but sometimes they have a very long delay. Any idea why?

### ISSUE THREAD

**Issue by gavin310** [deliciousbrains/wp-background-processing#88]
I love this library since Action Scheduler wasn't working for me (AS took way too long to start processing, whereas WP BG Processing only has a short delay usually). 95% of the time it works great, but occasionally the background processes take very long to start, like 5+ minutes. When this happens I've tried navigating through WordPress, because from what I understand the queue processing is triggered by requests to the backend, due to not having a cron scheduler. However, navigating through the CMS doesn't seem to kickstart the stalled background processing. Does anyone happen to know what might be causing this and how to go about fixing it?

**Comment by anastis** [comment]
A little late to the game, but I just had the same issue. After some digging I found out that the library uses wp cron internally.
In installations with Action Scheduler active (such as with WooCommerce), wp-background-processing jobs seem to run more consistently. I think it is because AS triggers wp cron every minute, whereas wp-background-processing adds a custom schedule for 5 minutes.
[Changing this value](https://github.com/deliciousbrains/wp-background-processing/blob/master/classes/wp-background-process.php#L416) to 1 seems to improve responsiveness, I'm not sure what other side-effects it could have though.

**Comment by ianmjones** [comment]
It sounds like the initial `dispatch()` after adding to queue and saving the batch is failing to start its background processing, but the healthcheck cron eventually sees the process isn't running and handles it. This means you're not getting the instant chained background processing, but instead just getting something processed every 5 minutes.

Chances are that there isn't an instance of `WP_Background_Process` created early enough to accept the spawned AJAX request, or the server doesn't know its own domain name as set for the site's URL.

**Comment by anastis** [comment]
Commenting in case it helps anyone in the future.

It looks like my problems were caused by the LiteSpeed WebServer (LSWS) which defaults to killing processes as soon as their connection is closed.

`WP_Async_Request::dispatch()` does a `wp_remote_post()` and sets `'timeout' => 0.01, 'blocking' => false`, which causes LSWS to kill the process immediately.

This LSWS behaviour can be disabled by setting up [No Abort](https://docs.litespeedtech.com/lsws/extapp/php/configuration/control/#no-abort).

I've also written a [KB article](https://www.cssigniter.com/kb/litespeed-web-server-enable-noabort/) detailing this, along with a usable `.htaccess` snippet.
